apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{ include "base.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  to:
    kind: Service
    name: {{ include "base.fullname" . }}
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None