# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build & Test Maven_App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name : Build Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Java Setup
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Build with Maven
      run: |
        ls
        echo $GOOGLE_APP_CREDENTIALS > ./google/google-credentials.json
        cd ./google
        ls -shl *
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ./google/google-credentials.json
        GOOGLE_APP_CREDENTIALS: ${{ secrets.GOOGLE_APP_CREDENTIALS }}
        #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: bash
      
