# This is a basic workflow that is manually triggered

name: Sonar Cloud Analysis
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Click True'
        # Default value if no value is explicitly provided
        default: 'True'
        # Input has to be provided for the workflow to run
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
   sonarcloud:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      run: |
          export SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
          env
      shell: bash
    - name: Java Setup
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Maven Sonar Push
      run: mvn -B package --file pom.xml -X
            
